# Generated by Django 4.1.3 on 2022-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='addressEmploye',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='cpEmployee',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
