# Generated by Django 4.1.3 on 2022-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0002_prestation_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='heureArrivee',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='heureDepart',
            field=models.TimeField(null=True),
        ),
    ]
