# Generated by Django 4.1.3 on 2022-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0004_alter_prestation_heurearrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='clientcommentaire',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
