# Generated by Django 4.1.3 on 2022-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0005_prestation_clientcommentaire_prestation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='heureArrivee',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='heureDepart',
            field=models.TimeField(null=True),
        ),
    ]
