# Generated by Django 4.1.3 on 2023-02-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0009_alter_prestation_heurearrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
