# Generated by Django 4.1.3 on 2023-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='emailClient',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
